### ISSUE TITLE
[Publish] Compliance to Plugin's guidelines - changes required

### ISSUE THREAD

**Issue by LBF38** [LBF38/obsidian-syncthing-integration#64]
[<img src="assets/Obsidian_software_logo.svg" height=100>](https://github.com/LBF38/obsidian-syncthing-integration/blob/6f0fd16a1850f9a91efd7254e81de93024a4f6d4/README.md#L4)
This is the old logo, you can get our new one here: <https://obsidian.md/brand>

["description": "This is a plugin for synchronizing your vault with Syncthing. It aims to integrate most syncthing features into Obsidian.",](https://github.com/LBF38/obsidian-syncthing-integration/blob/6f0fd16a1850f9a91efd7254e81de93024a4f6d4/manifest.json#L6)
We have recently published a guide for plugin descriptions to follow here: https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple.
Avoid including sentences like "This is a plugin" in your description.

[//! Remember to rename these classes and interfaces!](https://github.com/LBF38/obsidian-syncthing-integration/blob/6f0fd16a1850f9a91efd7254e81de93024a4f6d4/src/main.ts#L22)
Remove this comment

[SyncthingPlugin.loadCount++;](https://github.com/LBF38/obsidian-syncthing-integration/blob/6f0fd16a1850f9a91efd7254e81de93024a4f6d4/src/main.ts#L51)
What's this variable for?
I don't see any reason for it to exist.

[import { exec } from "child_process";](https://github.com/LBF38/obsidian-syncthing-integration/blob/6f0fd16a1850f9a91efd7254e81de93024a4f6d4/src/data/syncthing_local_datasource.ts#L1)
These imports are only available from a NodeJS runtime, which means that this will throw errors on Mobile (that's a problem since you have `isDesktopOnly` marked as `false` in your manifest.json file.
For mobile support you should import this conditionally by checking for `Platform.isDesktop` and then using `const {exec} = require('child_process');` inside the `runSyncthingCommand` method.

[// Banner](https://github.com/LBF38/obsidian-syncthing-integration/blob/6f0fd16a1850f9a91efd7254e81de93024a4f6d4/src/views/settings_tab.ts#L21-L42)
You should keep your plugin settings simple, that also means that this banner should get removed.

[syncthingImg.style.height = "100px";](https://github.com/LBF38/obsidian-syncthing-integration/blob/6f0fd16a1850f9a91efd7254e81de93024a4f6d4/src/views/settings_tab.ts#L38)
You should avoid assigning styles via JavaScript or in HTML and instead move all these styles into CSS so that they are more easily adaptable by themes and snippets.

[containerEl.createEl("h1", {](https://github.com/LBF38/obsidian-syncthing-integration/blob/6f0fd16a1850f9a91efd7254e81de93024a4f6d4/src/views/settings_tab.ts#L71-L73)
[Only use headings under settings if you have more than one section. ](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Only+use+headings+under+settings+if+you+have+more+than+one+section.)
[Avoid "settings" in settings headings](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+%22settings%22+in+settings+headings)

_Originally posted by @joethei in https://github.com/obsidianmd/obsidian-releases/pull/2083#issuecomment-1607726704_

Need to fix some parts of the plugin before being approved for publishing it in Obsidian's community plugins !

## TODOs
- [x] Change Obsidian logo for newer version
- [x] Change Plugin description
- [x] Clean the code and remove unnecessary comments
- [x] Add mobile support => manage imports for desktop / mobile. #63 
- [ ] Remove the banner in the settings page
- [ ] Add styles in CSS, not in JS (better for themes)
- [x] Avoid "settings" in settings headings
